driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: fedora-24
  - name: opensuse-13.2
  - name: opensuse-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: create
    run_list:
      - recipe[fake::create]
  - name: persist
    run_list:
      - recipe[fake::persist]
  - name: remove
    run_list:
      - recipe[fake::remove]
