driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-latest
    driver:
      box: bento/fedora-27
  - name: opensuse-leap
    driver:
      box: bento/opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: create
    run_list:
      - recipe[test::create]
  - name: create_swappiness
    run_list:
      - recipe[test::create_swappiness]
  - name: persist
    run_list:
      - recipe[test::persist]
  - name: remove
    run_list:
      - recipe[test::remove]
